### ISSUE TITLE
FTE staff categories

### ISSUE THREAD

**Issue by glorwlin** [TUOS-COM6911-2017/proj-ref2017#11]
@jkarpowicz has been asking this question and I found out the answer today:)

FTE - full-time equivalent staff
- This should be the number of full-time equivalent staff in an institiution related to a specific UOA.

Category A - academics 
Category C - honoraries i.e. unpaid staff
- It is normal that universities only have category A staff contributing to REF.

I hope the above answers the question.

**Comment by jkarpowicz** [comment]
Thank you Gloria - it explains our doubts

**Comment by glorwlin** [comment]
Detailed explanation can be found here:
[https://www.imperial.ac.uk/research-and-innovation/about-imperial-research/ref/background/submissions/staff/](url)

**Comment by Rawaida** [comment]
Have a look at this document (uploaded earlier by @GChrysostomou) Go to Part 3 - page 17. Details of the category were mentioned. (Very detailed! 😸 )
https://github.com/TUOS-COM6911-2017/proj-ref2017/blob/master/literature-review/GOS%20including%20addendum.pdf
